### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'

### ISSUE THREAD

**Issue by akbarali2019** [yasarniyazoglu/YoloV5-and-DeepSort-Custom-Dataset#1]
When I try track.py it is giving this error: 
FileNotFoundError: [Errno 2] No such file or directory: 'deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7'

I have checked your repo and mikel-brostrom repo, but I couldnot find .t7 file. When I watched your video on youtube after the command [python track.py --yolo_weights last.pt --source vid1.mp4 --save-vid] .t7 file automatically downloaded  in your case. I did same procedures including --recurse-submodules but it's giving this error. 

I also downloaded .t7 file from other sources and put the file inside checkpoint, but when I try track.py it's giving another error:  
Fusing layers...
Model Summary: 224 layers, 7053910 parameters, 0 gradients
Traceback (most recent call last):
  File "track.py", line 216, in <module>
    detect(args)
  File "track.py", line 85, in detect
    for frame_idx, (path, img, im0s, vid_cap) in enumerate(dataset):
ValueError: too many values to unpack (expected 4)

How can I solve the issue? Please help!

**Comment by yasarniyazoglu** [comment]
@akbarali2019 Hello. From track.py parser.add_argument('--deep_sort_weights', type=str, default='deep_sort_pytorch/deep_sort/deep/checkpoint/ckpt.t7', help='ckpt.t7 path') There is this code on line 194 here Can you give the path as default and try?

**Comment by akbarali2019** [comment]
Hi I have solved this issue. Thanks

**Comment by m-fahad-nasir** [comment]
Hi,
Same Issue can you Guide me how to Fix it.

**Comment by wn-reat** [comment]
请问怎么解决的呢
